modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "paperthinmaps"
version = "${version}"
displayName = "Paper Thin Maps"
authors = "Giro"
description = '''
Makes maps thin as paper.
'''
#logoFile = ""

[[dependencies.paperthinmaps]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paperthinmaps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paperthinmaps]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
